### ISSUE TITLE
OMIM Phenotype entries do not contain all associated genes

### ISSUE THREAD

**Issue by tayloramurphy** [solvebio/solvebio#1]
The phenotype database does present the full set of genes that are associated with a specific disorder. A great example is [OMIM 211980 (Lung Cancer)](http://omim.org/entry/211980). Associated with this disorder are the following genes:

`["FASLG","CASP8","DLEC1","RASSF1","PIK3CA","IRF1","PRKN","EGFR","BRAF","MAP3K8","ERCC6","SLC22A1L","PPP2R1B","KRAS","ERBB2","CYP2A6"]`

What's returned with [211980 on SolveBio](https://www.solvebio.com/library/OMIM/2.0.0-2015-07-10/Phenotypes?q=211980) is just FASLG and it's associated synonyms. It's actually more confusing because the returned symbols make them seem like individual entries when really they're all just synonyms of [FASLG (according to HGNC)](http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:11936):

`["FASLG", "TNFSF6", "APT1LG1", "FASL", "ALPS1B"]`

A solution could be to return an array for `omim_id_gene` of all genes associated with the disorder as well as returning just the proper HGNC symbols for `gene_symbol`. It seems to me that returning the synonyms of a gene on an OMIM phenotype page isn't as useful. It would be useful on the Genes record.

This same issue applies to the cytogenetic locations as well.

**Comment by dandanxu** [comment]
Hey Taylor, I see what you mean. I'll look into getting this fixed with the full set of associated genes (and cytogenetic locations) instead of just the first associated gene. Should have a new version up within a day or two with the fix.

**Comment by dandanxu** [comment]
Just put up a new version of OMIM that fixes this issue in the Phenotypes dataset (see https://www.solvebio.com/library/OMIM/2.1.0-2015-08-10/Phenotypes). [211980](https://www.solvebio.com/library/OMIM/2.1.0-2015-08-10/Phenotypes?q=211980) now returns only the proper HGNC gene symbols for `gene_symbol`. 
` 'gene_symbol': ['FASLG', 'CASP8', 'DLEC1', 'RASSF1', 'PIK3CA', 'IRF1', 'PRKN', 'EGFR', 'EGFR', 'EGFR', 'BRAF', 'MAP3K8', 'ERCC6', 'SLC22A1L', 'PPP2R1B', 'KRAS', 'ERBB2', 'CYP2A6'],` as expected. Cytogenetic locations has also been fixed.

We also return a separate `mapped_gene` object that describes the type of mapping between the gene and each individual phenotype. I did remove `genomic_coordinates` for each phenotype, since it only returns the first mapped gene in the list instead of every mapped gene. Is searching for phenotypes by specific genomic positions something necessary? If so, we'll figure out a way to put them in there.

Hope that helps! Let us know if anything else seems off.

**Comment by tayloramurphy** [comment]
That looks great. I'm assuming that the order of the items in the array is consistent across the fields? That is, if I just did a `zip( mapped_gene.gene_symbol_all, omim_id_gene)` everything would line up correctly?

If that's the case, then I think this issue can be closed. Thanks Dandan!

**Comment by dandanxu** [comment]
I noticed I accidentally kept the `mapped_gene.omim_id` as the original phenotype omim ID instead of the mapped gene omim id. That is fixed now in https://www.solvebio.com/library/OMIM/2.1.1-2015-08-10/Phenotypes. The order of all the items in the arrays are consistent across fields, but now with the right `mapped_gene.omim_id`, you can just do 

```
Dataset.retrieve('OMIM/2.1.1-2015-08-10/Phenotypes').query('211980')[0].get('mapped_gene')
           Out<9>: 
[{'gene_symbol': 'FASLG',
  'gene_symbol_all': ['FASLG', 'TNFSF6', 'APT1LG1', 'FASL', 'ALPS1B'],
  'inheritance': 'Autosomal recessive',
  'mapping_key': 'Molecular basis known, mutation found in gene',
  'omim_id': '134638',
  'phenotype': '{Lung cancer, susceptibility to}',
  'phenotypic_series': None},
 {'gene_symbol': 'CASP8',
  'gene_symbol_all': ['CASP8', 'MCH5', 'ALPS2B'],
  'inheritance': 'Autosomal recessive',
  'mapping_key': 'Molecular basis known, mutation found in gene',
  'omim_id': '601763',
  'phenotype': '{Lung cancer, protection against}',
  'phenotypic_series': None},
....
```
and get a nested dictionary with the proper grouping guaranteed. 
Ok! That should *actually* fix the issue. Feel free to re-open if you'd like the data formatted in a different way, etc.
